parti_de_gauche_elections:
    resource: "@PartiDeGaucheElectionsBundle/Controller/"
    type:     annotation
    prefix:   /

# Sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
