parti_de_gauche_elections:
    resource: "@PartiDeGaucheElectionsBundle/Controller/"
    type:     annotation
    prefix:   /

#login
login_check:
    path: /login_check

logout:
    path:   /logout

# Sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
